"""
CSE Ticker Alias Map
Maps common names, abbreviations, and variations to official CSE ticker symbols.
The CSE API uses the format "SYMBOL.N0000" internally.

Add more tickers as needed — this is a starter set of ~50 popular stocks.
Run `python -m utils.ticker_map update` to auto-populate from CSE API.
"""

# Official ticker -> CSE API symbol mapping
TICKER_TO_CSE = {
    "AAF": "AAF.N0000",
    "AAIC": "AAIC.N0000",
    "ABAN": "ABAN.N0000",
    "ABL": "ABL.N0000",
    "ACL": "ACL.N0000",
    "ACME": "ACME.N0000",
    "AEL": "AEL.N0000",
    "AFS": "AFS.N0000",
    "AFSL": "AFSL.N0000",
    "AGAL": "AGAL.N0000",
    "AGPL": "AGPL.N0000",
    "AGST": "AGST.N0000",
    "AHPL": "AHPL.N0000",
    "AHUN": "AHUN.N0000",
    "ALLI": "ALLI.N0000",
    "ALUM": "ALUM.N0000",
    "AMF": "AMF.N0000",
    "AMSL": "AMSL.N0000",
    "APLA": "APLA.N0000",
    "ASCO": "ASCO.N0000",
    "ASHO": "ASHO.N0000",
    "ASIR": "ASIR.N0000",
    "ASIY": "ASIY.N0000",
    "ASPH": "ASPH.N0000",
    "ATL": "ATL.N0000",
    "ATLL": "ATLL.N0000",
    "AUTO": "AUTO.N0000",
    "BALA": "BALA.N0000",
    "BERU": "BERU.N0000",
    "BFL": "BFL.N0000",
    "BFN": "BFN.N0000",
    "BIL": "BIL.N0000",
    "BOGA": "BOGA.N0000",
    "BOPL": "BOPL.N0000",
    "BPPL": "BPPL.N0000",
    "BREW": "BREW.N0000",
    "BRR": "BRR.N0000",
    "BRWN": "BRWN.N0000",
    "BUKI": "BUKI.N0000",
    "CABO": "CABO.N0000",
    "CALF": "CALF.N0000",
    "CALH": "CALH.N0000",
    "CALT": "CALT.N0000",
    "CARE": "CARE.N0000",
    "CARG": "CARG.N0000",
    "CARS": "CARS.N0000",
    "CBNK": "CBNK.N0000",
    "CCS": "CCS.N0000",
    "CDB": "CDB.N0000",
    "CERA": "CERA.N0000",
    "CFI": "CFI.N0000",
    "CFIN": "CFIN.N0000",
    "CFLB": "CFLB.N0000",
    "CFVF": "CFVF.N0000",
    "CHL": "CHL.N0000",
    "CHMX": "CHMX.N0000",
    "CHOT": "CHOT.N0000",
    "CIC": "CIC.N0000",
    "CIND": "CIND.N0000",
    "CINS": "CINS.N0000",
    "CINV": "CINV.N0000",
    "CIT": "CIT.N0000",
    "CITH": "CITH.N0000",
    "CITW": "CITW.N0000",
    "CLND": "CLND.N0000",
    "COCO": "COCO.N0000",
    "COCR": "COCR.N0000",
    "COLO": "COLO.N0000",
    "COMB": "COMB.N0000",
    "COMD": "COMD.N0000",
    "CONN": "CONN.N0000",
    "COOP": "COOP.N0000",
    "CPRT": "CPRT.N0000",
    "CRL": "CRL.N0000",
    "CSD": "CSD.N0000",
    "CSLK": "CSLK.N0000",
    "CTBL": "CTBL.N0000",
    "CTC": "CTC.N0000",
    "CTEA": "CTEA.N0000",
    "CTHR": "CTHR.N0000",
    "CTLD": "CTLD.N0000",
    "CWL": "CWL.N0000",
    "CWM": "CWM.N0000",
    "DFCC": "DFCC.N0000",
    "DIAL": "DIAL.N0000",
    "DIMO": "DIMO.N0000",
    "DIPD": "DIPD.N0000",
    "DIST": "DIST.N0000",
    "DOCK": "DOCK.N0000",
    "DPL": "DPL.N0000",
    "EAST": "EAST.N0000",
    "EBCR": "EBCR.N0000",
    "ECL": "ECL.N0000",
    "EDEN": "EDEN.N0000",
    "ELPL": "ELPL.N0000",
    "EMER": "EMER.N0000",
    "EML": "EML.N0000",
    "ETWO": "ETWO.N0000",
    "EXT": "EXT.N0000",
    "FCT": "FCT.N0000",
    "GEST": "GEST.N0000",
    "GHLL": "GHLL.N0000",
    "GLAS": "GLAS.N0000",
    "GRAN": "GRAN.N0000",
    "GREG": "GREG.N0000",
    "GUAR": "GUAR.N0000",
    "HAPU": "HAPU.N0000",
    "HARI": "HARI.N0000",
    "HASU": "HASU.N0000",
    "HAYC": "HAYC.N0000",
    "HAYL": "HAYL.N0000",
    "HBS": "HBS.N0000",
    "HDFC": "HDFC.N0000",
    "HELA": "HELA.N0000",
    "HEXP": "HEXP.N0000",
    "HHL": "HHL.N0000",
    "HNB": "HNB.N0000",
    "HNBF": "HNBF.N0000",
    "HOPL": "HOPL.N0000",
    "HPFL": "HPFL.N0000",
    "HPL": "HPL.N0000",
    "HPWR": "HPWR.N0000",
    "HSIG": "HSIG.N0000",
    "HUNA": "HUNA.N0000",
    "HUNT": "HUNT.N0000",
    "HVA": "HVA.N0000",
    "JAT": "JAT.N0000",
    "JETS": "JETS.N0000",
    "JFP": "JFP.N0000",
    "JINS": "JINS.N0000",
    "JKH": "JKH.N0000",
    "JKL": "JKL.N0000",
    "KAHA": "KAHA.N0000",
    "KCAB": "KCAB.N0000",
    "KFP": "KFP.N0000",
    "KGAL": "KGAL.N0000",
    "KHC": "KHC.N0000",
    "KHL": "KHL.N0000",
    "KOTA": "KOTA.N0000",
    "KPHL": "KPHL.N0000",
    "KVAL": "KVAL.N0000",
    "KZOO": "KZOO.N0000",
    "LALU": "LALU.N0000",
    "LAMB": "LAMB.N0000",
    "LCBF": "LCBF.N0000",
    "LCEY": "LCEY.N0000",
    "LDEV": "LDEV.N0000",
    "LFIN": "LFIN.N0000",
    "LGIL": "LGIL.N0000",
    "LGL": "LGL.N0000",
    "LHCL": "LHCL.N0000",
    "LHL": "LHL.N0000",
    "LIOC": "LIOC.N0000",
    "LION": "LION.N0000",
    "LITE": "LITE.N0000",
    "LLUB": "LLUB.N0000",
    "LMF": "LMF.N0000",
    "LOFC": "LOFC.N0000",
    "LOLC": "LOLC.N0000",
    "LPL": "LPL.N0000",
    "LPRT": "LPRT.N0000",
    "LUMX": "LUMX.N0000",
    "LVEF": "LVEF.N0000",
    "LVEN": "LVEN.N0000",
    "LWL": "LWL.N0000",
    "MADU": "MADU.N0000",
    "MAL": "MAL.N0000",
    "MARA": "MARA.N0000",
    "MASK": "MASK.N0000",
    "MBSL": "MBSL.N0000",
    "MCPL": "MCPL.N0000",
    "MDL": "MDL.N0000",
    "MEL": "MEL.N0000",
    "MELS": "MELS.N0000",
    "MERC": "MERC.N0000",
    "MFPE": "MFPE.N0000",
    "MGT": "MGT.N0000",
    "MHDL": "MHDL.N0000",
    "MRH": "MRH.N0000",
    "MSL": "MSL.N0000",
    "MULL": "MULL.N0000",
    "NAMU": "NAMU.N0000",
    "NDB": "NDB.N0000",
    "NEH": "NEH.N0000",
    "NHL": "NHL.N0000",
    "NTB": "NTB.N0000",
    "ODEL": "ODEL.N0000",
    "OFEQ": "OFEQ.N0000",
    "ONAL": "ONAL.N0000",
    "OSEA": "OSEA.N0000",
    "PABC": "PABC.N0000",
    "PACK": "PACK.N0000",
    "PALM": "PALM.N0000",
    "PAP": "PAP.N0000",
    "PARA": "PARA.N0000",
    "PARQ": "PARQ.N0000",
    "PEG": "PEG.N0000",
    "PHAR": "PHAR.N0000",
    "PINS": "PINS.N0000",
    "PKME": "PKME.N0000",
    "PLC": "PLC.N0000",
    "PLR": "PLR.N0000",
    "PMB": "PMB.N0000",
    "RAL": "RAL.N0000",
    "RCH": "RCH.N0000",
    "RCL": "RCL.N0000",
    "REEF": "REEF.N0000",
    "RENU": "RENU.N0000",
    "REXP": "REXP.N0000",
    "RFL": "RFL.N0000",
    "RGEM": "RGEM.N0000",
    "RHL": "RHL.N0000",
    "RHTL": "RHTL.N0000",
    "RICH": "RICH.N0000",
    "RIL": "RIL.N0000",
    "RPBH": "RPBH.N0000",
    "RWSL": "RWSL.N0000",
    "SAMP": "SAMP.N0000",
    "SCAP": "SCAP.N0000",
    "SDB": "SDB.N0000",
    "SDF": "SDF.N0000",
    "SEMB": "SEMB.N0000",
    "SERV": "SERV.N0000",
    "SEYB": "SEYB.N0000",
    "SFCL": "SFCL.N0000",
    "SFIN": "SFIN.N0000",
    "SHAW": "SHAW.N0000",
    "SHL": "SHL.N0000",
    "SHOT": "SHOT.N0000",
    "SIGV": "SIGV.N0000",
    "SIL": "SIL.N0000",
    "SINH": "SINH.N0000",
    "SINS": "SINS.N0000",
    "SIRA": "SIRA.N0000",
    "SLTL": "SLTL.N0000",
    "SMOT": "SMOT.N0000",
    "SOY": "SOY.N0000",
    "SPEN": "SPEN.N0000",
    "STAF": "STAF.N0000",
    "SUN": "SUN.N0000",
    "TAFL": "TAFL.N0000",
    "TAJ": "TAJ.N0000",
    "TANG": "TANG.N0000",
    "TAP": "TAP.N0000",
    "TESS": "TESS.N0000",
    "TILE": "TILE.N0000",
    "TJL": "TJL.N0000",
    "TKYO": "TKYO.N0000",
    "TPL": "TPL.N0000",
    "TRAN": "TRAN.N0000",
    "TSML": "TSML.N0000",
    "TYRE": "TYRE.N0000",
    "UAL": "UAL.N0000",
    "UBC": "UBC.N0000",
    "UBF": "UBF.N0000",
    "UCAR": "UCAR.N0000",
    "UDPL": "UDPL.N0000",
    "UML": "UML.N0000",
    "VFIN": "VFIN.N0000",
    "VLL": "VLL.N0000",
    "VONE": "VONE.N0000",
    "VPEL": "VPEL.N0000",
    "WAPO": "WAPO.N0000",
    "WATA": "WATA.N0000",
    "WIND": "WIND.N0000",
    "WLTH": "WLTH.N0000",
    "YORK": "YORK.N0000",
}

# Alias -> official ticker mapping
# Maps common names, abbreviations, typos, Sinhala/Tamil references
ALIASES = {
    "aaf": "AAF",
    "aaic": "AAIC",
    "aban": "ABAN",
    "abans electricals": "ABAN",
    "abans finance": "AFSL",
    "abl": "ABL",
    "access engineering": "AEL",
    "acl": "ACL",
    "acl cables": "ACL",
    "acl plastics": "APLA",
    "acme": "ACME",
    "acme printing": "ACME",
    "acme printing & packaging": "ACME",
    "ael": "AEL",
    "afs": "AFS",
    "afsl": "AFSL",
    "agal": "AGAL",
    "agalawatte  plantations": "AGAL",
    "agarapatana plantations": "AGPL",
    "agpl": "AGPL",
    "agst": "AGST",
    "agstar": "AGST",
    "ahpl": "AHPL",
    "ahun": "AHUN",
    "aitken spence": "SPEN",
    "aitken spence hotel": "AHPL",
    "aitken spence hotel holdings": "AHUN",
    "alli": "ALLI",
    "alliance finance": "ALLI",
    "alliance finance company": "ALLI",
    "alpha fire": "AFS",
    "alpha fire services": "AFS",
    "alum": "ALUM",
    "alumex": "ALUM",
    "aluminium": "ALUM",
    "amana bank": "ABL",
    "amana takaful": "ATL",
    "amana takaful life": "ATLL",
    "ambeon capital": "TAP",
    "ambeon holdings": "GREG",
    "amf": "AMF",
    "amsl": "AMSL",
    "apla": "APLA",
    "arpico": "RCL",
    "asco": "ASCO",
    "asho": "ASHO",
    "asia asset": "AAF",
    "asia asset finance": "AAF",
    "asia insurance": "ASIY",
    "asia siyaka": "ASIY",
    "asia siyaka commodities": "ASIY",
    "asian hotels": "AHPL",
    "asian hotels and properties": "AHPL",
    "asir": "ASIR",
    "asiri hospital": "ASIR",
    "asiri hospital holdings": "ASIR",
    "asiri surgical": "AMSL",
    "asiri surgical hospital": "AMSL",
    "asiy": "ASIY",
    "asph": "ASPH",
    "associated motor": "AMF",
    "associated motor finance company": "AMF",
    "atl": "ATL",
    "atll": "ATLL",
    "auto": "AUTO",
    "b p": "BPPL",
    "b p p l holdings": "BPPL",
    "bairaha farms": "BFL",
    "bala": "BALA",
    "balangoda  plantations": "BALA",
    "bansei royal": "BRR",
    "bansei royal resorts hikkaduwa": "BRR",
    "beru": "BERU",
    "beruwala resorts": "BERU",
    "bfl": "BFL",
    "bfn": "BFN",
    "bil": "BIL",
    "boga": "BOGA",
    "bogala graphite": "BOGA",
    "bogala graphite lanka": "BOGA",
    "bogawantalawa tea": "BOPL",
    "bogawantalawa tea estates": "BOPL",
    "bopl": "BOPL",
    "bppl": "BPPL",
    "brew": "BREW",
    "brown &": "BRWN",
    "brown & company": "BRWN",
    "browns": "BIL",
    "browns investments": "BIL",
    "brr": "BRR",
    "brwn": "BRWN",
    "buki": "BUKI",
    "bukit": "BUKI",
    "bukit darah": "BUKI",
    "c i": "CIC",
    "c i c holdings": "CIC",
    "c m": "COLO",
    "c m holdings": "COLO",
    "c t": "CTHR",
    "c t holdings": "CTHR",
    "c t land development": "CTLD",
    "c. w.": "CWM",
    "c. w. mackie": "CWM",
    "cable solutions": "CSLK",
    "cabo": "CABO",
    "calf": "CALF",
    "calh": "CALH",
    "calt": "CALT",
    "capital alliance": "CALH",
    "capital alliance holdings": "CALH",
    "care": "CARE",
    "carg": "CARG",
    "cargills": "CARG",
    "cargills (ceylon)": "CARG",
    "cargills bank": "CBNK",
    "cargills ceylon": "CARG",
    "cargo boat": "CABO",
    "cargo boat development company": "CABO",
    "cars": "CARS",
    "carson": "CARS",
    "carson cumberbatch": "CARS",
    "carsons": "CARS",
    "cbnk": "CBNK",
    "ccs": "CCS",
    "cdb": "CDB",
    "central finance": "CFIN",
    "central finance company": "CFIN",
    "central industries": "CIND",
    "cera": "CERA",
    "ceylinco holdings": "CINS",
    "ceylinco insurance": "CINS",
    "ceylon beverage": "BREW",
    "ceylon beverage holdings": "BREW",
    "ceylon cold": "CCS",
    "ceylon cold stores": "CCS",
    "ceylon grain": "GRAN",
    "ceylon grain elevators": "GRAN",
    "ceylon guardian": "GUAR",
    "ceylon guardian investment trust": "GUAR",
    "ceylon hospitals": "CHL",
    "ceylon hotels": "CHOT",
    "ceylon hotels corporation": "CHOT",
    "ceylon investment": "CINV",
    "ceylon land": "KZOO",
    "ceylon land & equity": "KZOO",
    "ceylon tea": "CTBL",
    "ceylon tea brokers": "CTBL",
    "ceylon tobacco": "CTC",
    "ceylon tobacco company": "CTC",
    "cfi": "CFI",
    "cfin": "CFIN",
    "cflb": "CFLB",
    "cfvf": "CFVF",
    "chemanex": "CHMX",
    "chevron lubricants": "LLUB",
    "chevron lubricants  lanka": "LLUB",
    "chl": "CHL",
    "chmx": "CHMX",
    "chot": "CHOT",
    "chrissworld": "CWL",
    "cic": "CIC",
    "cind": "CIND",
    "cins": "CINS",
    "cinv": "CINV",
    "cit": "CIT",
    "cith": "CITH",
    "citizens development": "CDB",
    "citizens development business finance": "CDB",
    "citrus leisure": "REEF",
    "citw": "CITW",
    "clnd": "CLND",
    "co-operative insurance": "COOP",
    "co-operative insurance company": "COOP",
    "coco": "COCO",
    "cocr": "COCR",
    "cold stores": "CCS",
    "colo": "COLO",
    "colombo city": "PHAR",
    "colombo city holdings": "PHAR",
    "colombo dockyard": "DOCK",
    "colombo fort": "CFI",
    "colombo fort investments": "CFI",
    "colombo investment": "CIT",
    "colombo investment trust": "CIT",
    "colombo land": "CLND",
    "colombo land and development company": "CLND",
    "comb": "COMB",
    "combank": "COMB",
    "comd": "COMD",
    "commercial bank": "COMB",
    "commercial bank of ceylon": "COMB",
    "commercial credit": "COCR",
    "commercial credit and finance": "COCR",
    "commercial development": "COMD",
    "commercial development company": "COMD",
    "conn": "CONN",
    "convenience foods": "SOY",
    "convenience foods lanka": "SOY",
    "coop": "COOP",
    "cprt": "CPRT",
    "crl": "CRL",
    "csd": "CSD",
    "cslk": "CSLK",
    "ct holdings": "CTBL",
    "ctbl": "CTBL",
    "ctc": "CTC",
    "ctea": "CTEA",
    "cthr": "CTHR",
    "ctld": "CTLD",
    "cwl": "CWL",
    "cwm": "CWM",
    "dankotuwa porcelain": "DPL",
    "dcsl": "DIST",
    "dfcc": "DFCC",
    "dfcc bank": "DFCC",
    "dial": "DIAL",
    "dialog": "DIAL",
    "dialog axiata": "DIAL",
    "dialog finance": "CALF",
    "diesel &": "DIMO",
    "diesel & motor engineering": "DIMO",
    "digital mobility": "PKME",
    "digital mobility solutions lanka": "PKME",
    "dilmah ceylon": "CTEA",
    "dilmah ceylon tea company": "CTEA",
    "dimo": "DIMO",
    "dipd": "DIPD",
    "dipped": "DIPD",
    "dipped products": "DIPD",
    "dist": "DIST",
    "distilleries": "DIST",
    "distilleries company": "DIST",
    "distilleries company of sri lanka": "DIST",
    "dock": "DOCK",
    "dolphin hotels": "STAF",
    "dpl": "DPL",
    "e -": "ECL",
    "e - channelling": "ECL",
    "e b": "EBCR",
    "e b creasy & company": "EBCR",
    "e m": "EML",
    "e m l consultants": "EML",
    "east": "EAST",
    "east west": "EAST",
    "east west properties": "EAST",
    "eastern merchants": "EMER",
    "ebcr": "EBCR",
    "ecl": "ECL",
    "eden": "EDEN",
    "eden hotel": "EDEN",
    "eden hotel lanka": "EDEN",
    "elpitiya plantations": "ELPL",
    "elpl": "ELPL",
    "emer": "EMER",
    "eml": "EML",
    "equity two": "ETWO",
    "etwo": "ETWO",
    "ex-pack corrugated": "PACK",
    "ex-pack corrugated cartons": "PACK",
    "ext": "EXT",
    "exterminators": "EXT",
    "fct": "FCT",
    "first capital": "CFVF",
    "first capital holdings": "CFVF",
    "first capital treasuries": "FCT",
    "galadari hotels": "GHLL",
    "galadari hotels (lanka)": "GHLL",
    "galle face": "WAPO",
    "galle face capital partners": "WAPO",
    "gest": "GEST",
    "gestetner of": "GEST",
    "gestetner of ceylon": "GEST",
    "ghll": "GHLL",
    "glas": "GLAS",
    "gran": "GRAN",
    "granbles": "GRAN",
    "greentech energy": "MEL",
    "greg": "GREG",
    "guar": "GUAR",
    "hapu": "HAPU",
    "hapugastenne plantations": "HAPU",
    "hari": "HARI",
    "harischandra mills": "HARI",
    "hasu": "HASU",
    "hatton national": "HNB",
    "hatton national bank": "HNB",
    "hatton plantations": "HPL",
    "hayc": "HAYC",
    "haycarb": "HAYC",
    "hayl": "HAYL",
    "hayleys": "HAYC",
    "hayleys fabric": "HAYC",
    "hayleys fibre": "HEXP",
    "hayleys leisure": "CONN",
    "hbs": "HBS",
    "hdfc": "HDFC",
    "hela": "HELA",
    "hela apparel": "HELA",
    "hela apparel holdings": "HELA",
    "hemas holdings": "HHL",
    "hexp": "HEXP",
    "hhl": "HHL",
    "hikkaduwa beach": "CITH",
    "hikkaduwa beach resort": "CITH",
    "hnb": "HNB",
    "hnb assurance": "HASU",
    "hnb finance": "HNBF",
    "hnbf": "HNBF",
    "hopl": "HOPL",
    "horana plantations": "HOPL",
    "hotel sigiriya": "HSIG",
    "housing development": "HDFC",
    "housing development finance corporation bank of sl": "HDFC",
    "hpfl": "HPFL",
    "hpl": "HPL",
    "hpwr": "HPWR",
    "hsenid business": "HBS",
    "hsenid business solutions": "HBS",
    "hsig": "HSIG",
    "huna": "HUNA",
    "hunas holdings": "HUNA",
    "hunt": "HUNT",
    "hunter &": "HUNT",
    "hunter & company": "HUNT",
    "hva": "HVA",
    "hva foods": "HVA",
    "industrial asphalts": "ASPH",
    "industrial asphalts (ceylon)": "ASPH",
    "ioc": "LIOC",
    "janashakthi finance": "BFN",
    "janashakthi insurance": "JINS",
    "jat": "JAT",
    "jat holdings": "JAT",
    "jets": "JETS",
    "jetwing symphony": "JETS",
    "jf packaging": "JFP",
    "jfp": "JFP",
    "jins": "JINS",
    "jkh": "JKH",
    "jkl": "JKL",
    "john keells": "JKH",
    "john keells holdings": "JKH",
    "john keells hotels": "KHL",
    "kaha": "KAHA",
    "kahawatte  plantations": "KAHA",
    "kaphruka": "KPHL",
    "kapruka": "KPHL",
    "kapruka holdings": "KPHL",
    "kcab": "KCAB",
    "keells": "JKH",
    "keells food": "KFP",
    "keells food products": "KFP",
    "kegalle  plantations": "KGAL",
    "kelani cables": "KCAB",
    "kelani tyres": "TYRE",
    "kelani valley": "KVAL",
    "kelani valley plantations": "KVAL",
    "kerner haus": "CPRT",
    "kerner haus global solutions": "CPRT",
    "kfp": "KFP",
    "kgal": "KGAL",
    "khc": "KHC",
    "khl": "KHL",
    "kota": "KOTA",
    "kotagala plantations": "KOTA",
    "kotmale holdings": "LAMB",
    "kphl": "KPHL",
    "kval": "KVAL",
    "kzoo": "KZOO",
    "l o": "LOLC",
    "l o l c holdings": "LOLC",
    "l v": "LVEF",
    "l v l energy fund": "LVEF",
    "lake house": "LPRT",
    "lake house printers & publishers": "LPRT",
    "lalu": "LALU",
    "lamb": "LAMB",
    "lanka aluminium": "LALU",
    "lanka aluminium industries": "LALU",
    "lanka ashok": "ASHO",
    "lanka ashok leyland": "ASHO",
    "lanka ceramic": "CERA",
    "lanka credit": "LCBF",
    "lanka credit and business finance": "LCBF",
    "lanka ioc": "LIOC",
    "lanka milk": "LMF",
    "lanka milk foods (cwe)": "LMF",
    "lanka realty": "ASCO",
    "lanka realty investments": "ASCO",
    "lanka tiles": "TILE",
    "lanka ventures": "LVEN",
    "lanka wall tile": "LWL",
    "lanka walltile": "LWL",
    "lankem ceylon": "LCEY",
    "lankem developments": "LDEV",
    "laugfs gas": "LGL",
    "laugfs power": "LPL",
    "laxapana": "LITE",
    "lb finance": "LFIN",
    "lcbf": "LCBF",
    "lcey": "LCEY",
    "ldev": "LDEV",
    "lee hedges": "SHAW",
    "lfin": "LFIN",
    "lgil": "LGIL",
    "lgl": "LGL",
    "lhcl": "LHCL",
    "lhl": "LHL",
    "lioc": "LIOC",
    "lion": "LION",
    "lion brewery": "LION",
    "lion brewery (ceylon)": "LION",
    "lite": "LITE",
    "llub": "LLUB",
    "lmf": "LMF",
    "lofc": "LOFC",
    "lolc": "LOLC",
    "lolc development": "LDEV",
    "lolc finance": "LFIN",
    "lolc general": "LGIL",
    "lolc general insurance": "LGIL",
    "lolc holdings": "LOLC",
    "lotus hydro": "HPFL",
    "lotus hydro power": "HPFL",
    "lpl": "LPL",
    "lprt": "LPRT",
    "luminex": "LUMX",
    "lumx": "LUMX",
    "lvef": "LVEF",
    "lven": "LVEN",
    "lwl": "LWL",
    "madu": "MADU",
    "madulsima  plantations": "MADU",
    "maharaja foods": "MFPE",
    "mahaweli coconut": "MCPL",
    "mahaweli coconut plantations": "MCPL",
    "mahaweli reach": "MRH",
    "mahaweli reach hotels": "MRH",
    "mal": "MAL",
    "malwatte valley": "MAL",
    "malwatte valley plantation": "MAL",
    "mara": "MARA",
    "marawila  resorts": "MARA",
    "mask": "MASK",
    "maskeliya plantations": "MASK",
    "mbsl": "MBSL",
    "mcpl": "MCPL",
    "mdl": "MDL",
    "mel": "MEL",
    "mels": "MELS",
    "melstacorp": "MELS",
    "merc": "MERC",
    "mercantile investments": "MERC",
    "mercantile investments and finance": "MERC",
    "mercantile shipping": "MSL",
    "mercantile shipping company": "MSL",
    "merchant bank": "MBSL",
    "merchant bank of sri lanka & finance": "MBSL",
    "mfpe": "MFPE",
    "mgt": "MGT",
    "mhdl": "MHDL",
    "millennium housing": "MHDL",
    "millennium housing developers": "MHDL",
    "mrh": "MRH",
    "msl": "MSL",
    "mull": "MULL",
    "muller &": "MULL",
    "muller & phipps (ceylon)": "MULL",
    "myland developments": "MDL",
    "namu": "NAMU",
    "namunukula plantations": "NAMU",
    "national development": "NDB",
    "national development bank": "NDB",
    "nations trust": "NTB",
    "nations trust bank": "NTB",
    "nawaloka hospitals": "NHL",
    "ndb": "NDB",
    "neh": "NEH",
    "nhl": "NHL",
    "ntb": "NTB",
    "odel": "ODEL",
    "ofeq": "OFEQ",
    "office equipment": "OFEQ",
    "on'ally holdings": "ONAL",
    "onal": "ONAL",
    "osea": "OSEA",
    "overseas realty": "OSEA",
    "overseas realty (ceylon)": "OSEA",
    "pabc": "PABC",
    "pack": "PACK",
    "palm": "PALM",
    "palm garden": "PALM",
    "palm garden hotels": "PALM",
    "pan asia": "PABC",
    "pan asia banking corporation": "PABC",
    "panasian power": "PAP",
    "pap": "PAP",
    "para": "PARA",
    "paragon ceylon": "PARA",
    "parq": "PARQ",
    "peg": "PEG",
    "pegasus hotels": "PEG",
    "pegasus hotels of ceylon": "PEG",
    "people's insurance": "PINS",
    "people's leasing": "PLC",
    "people's leasing & finance": "PLC",
    "pgp glass": "GLAS",
    "pgp glass ceylon": "GLAS",
    "phar": "PHAR",
    "pins": "PINS",
    "pkme": "PKME",
    "plc": "PLC",
    "plr": "PLR",
    "pmb": "PMB",
    "pmf finance": "PMB",
    "prime lands": "PLR",
    "prime lands residencies": "PLR",
    "printcare": "CARE",
    "r i": "RIL",
    "r i l property": "RIL",
    "radiant gems": "RGEM",
    "radiant gems international": "RGEM",
    "raigam wayamba": "RWSL",
    "raigam wayamba salterns": "RWSL",
    "ral": "RAL",
    "ramboda falls": "RFL",
    "rch": "RCH",
    "rcl": "RCL",
    "reef": "REEF",
    "renu": "RENU",
    "renuka agri": "RAL",
    "renuka agri foods": "RAL",
    "renuka city": "RENU",
    "renuka city hotels.": "RENU",
    "renuka foods": "COCO",
    "renuka holdings": "RHL",
    "renuka hotels": "RCH",
    "resus energy": "HPWR",
    "rexp": "REXP",
    "rfl": "RFL",
    "rgem": "RGEM",
    "rhl": "RHL",
    "rhtl": "RHTL",
    "rich": "RICH",
    "richard pieris": "RCL",
    "richard pieris and company": "RICH",
    "richard pieris exports": "REXP",
    "ril": "RIL",
    "royal ceramics": "RCL",
    "royal ceramics lanka": "RCL",
    "royal palms": "RPBH",
    "royal palms beach hotels": "RPBH",
    "rpbh": "RPBH",
    "rwsl": "RWSL",
    "samp": "SAMP",
    "sampath": "SAMP",
    "sampath bank": "SAMP",
    "samson international": "SIL",
    "sanasa development": "SDB",
    "sanasa development bank": "SDB",
    "sarvodaya development": "SDF",
    "sarvodaya development finance": "SDF",
    "sathosa motors": "SMOT",
    "scap": "SCAP",
    "sdb": "SDB",
    "sdf": "SDF",
    "semb": "SEMB",
    "senkadagala finance": "SFCL",
    "senkadagala finance company": "SFCL",
    "serendib hotels": "SHOT",
    "serv": "SERV",
    "seyb": "SEYB",
    "seylan bank": "SEYB",
    "seylan developments": "CSD",
    "sfcl": "SFCL",
    "sfin": "SFIN",
    "shaw": "SHAW",
    "shl": "SHL",
    "shot": "SHOT",
    "sierra cables": "SIRA",
    "sigiriya village": "SIGV",
    "sigiriya village hotels": "SIGV",
    "sigv": "SIGV",
    "sil": "SIL",
    "singer (sri": "SINS",
    "singer (sri lanka)": "SINS",
    "singer finance": "SFIN",
    "singer finance lanka": "SFIN",
    "singhe hospitals": "SINH",
    "sinh": "SINH",
    "sins": "SINS",
    "sira": "SIRA",
    "sltl": "SLTL",
    "smb finance": "SEMB",
    "smot": "SMOT",
    "softlogic": "SHL",
    "softlogic capital": "SCAP",
    "softlogic finance": "CRL",
    "softlogic holdings": "SHL",
    "softlogic life": "AAIC",
    "softlogic life insurance": "AAIC",
    "soy": "SOY",
    "spen": "SPEN",
    "spence": "SPEN",
    "sri lanka": "SLTL",
    "sri lanka telecom": "SLTL",
    "staf": "STAF",
    "sun": "SUN",
    "sunshine": "SINS",
    "sunshine holdings": "SINS",
    "swisstek (ceylon)": "PARQ",
    "tafl": "TAFL",
    "taj": "TAJ",
    "taj lanka": "TJL",
    "tal lanka": "TAJ",
    "tal lanka hotels": "TAJ",
    "talawakelle tea": "TPL",
    "talawakelle tea estates": "TPL",
    "tang": "TANG",
    "tangerine beach": "TANG",
    "tangerine beach hotels": "TANG",
    "tap": "TAP",
    "tea smallholder": "TSML",
    "tea smallholder factories": "TSML",
    "teejay lanka": "TJL",
    "tess": "TESS",
    "tess agro": "TESS",
    "the  lighthouse  hotel": "LHL",
    "the autodrome": "AUTO",
    "the colombo": "CFLB",
    "the colombo fort land and building": "CFLB",
    "the fortress": "RHTL",
    "the fortress resorts": "RHTL",
    "the kandy": "KHC",
    "the kandy hotels company (1938)": "KHC",
    "the kingsbury": "SERV",
    "the lanka": "LHCL",
    "the lanka hospitals corporation": "LHCL",
    "the lighthouse": "LHL",
    "the nuwara": "NEH",
    "the nuwara eliya hotels company": "NEH",
    "three acre": "TAFL",
    "three acre farms": "TAFL",
    "tile": "TILE",
    "tjl": "TJL",
    "tkyo": "TKYO",
    "tobacco": "CTC",
    "tokyo": "TKYO",
    "tokyo cement": "TKYO",
    "tokyo cement company (lanka)": "TKYO",
    "tpl": "TPL",
    "tran": "TRAN",
    "trans asia": "TRAN",
    "trans asia hotels": "TRAN",
    "tsml": "TSML",
    "tyre": "TYRE",
    "ual": "UAL",
    "ub finance": "UBF",
    "ubc": "UBC",
    "ubf": "UBF",
    "ucar": "UCAR",
    "udapussellawa  plantations": "UDPL",
    "udpl": "UDPL",
    "uml": "UML",
    "union assurance": "UAL",
    "union bank": "UBC",
    "union bank of colombo": "UBC",
    "union chemicals": "UCAR",
    "union chemicals lanka": "UCAR",
    "united motors": "UML",
    "united motors lanka": "UML",
    "vallibel finance": "VFIN",
    "vallibel one": "VONE",
    "vallibel power": "VPEL",
    "vallibel power erathna": "VPEL",
    "vfin": "VFIN",
    "vidullanka": "VLL",
    "vll": "VLL",
    "vone": "VONE",
    "vpel": "VPEL",
    "walltile": "LWL",
    "wapo": "WAPO",
    "waskaduwa beach": "CITW",
    "waskaduwa beach resort": "CITW",
    "wata": "WATA",
    "watawala": "WATA",
    "watawala  plantations": "WATA",
    "watawala plantations": "WATA",
    "wealthtrust securities": "WLTH",
    "wind": "WIND",
    "windforce": "WIND",
    "wlth": "WLTH",
    "york": "YORK",
    "york arcade": "YORK",
    "york arcade holdings": "YORK",
}

# Sector classification
SECTORS = {
    "AAF": "Finance",
    "AAIC": "Insurance",
    "ABAN": "Energy",
    "ABL": "Banking",
    "ACL": "Diversified",
    "ACME": "Diversified",
    "AEL": "Construction",
    "AFS": "Diversified",
    "AFSL": "Finance",
    "AGAL": "Diversified",
    "AGPL": "Diversified",
    "AGST": "Diversified",
    "AHPL": "Hotels",
    "AHUN": "Hotels",
    "ALLI": "Finance",
    "ALUM": "Manufacturing",
    "AMF": "Finance",
    "AMSL": "Healthcare",
    "APLA": "Diversified",
    "ASCO": "Diversified",
    "ASHO": "Diversified",
    "ASIR": "Healthcare",
    "ASIY": "Insurance",
    "ASPH": "Diversified",
    "ATL": "Diversified",
    "ATLL": "Insurance",
    "AUTO": "Diversified",
    "BALA": "Diversified",
    "BERU": "Hotels",
    "BFL": "Diversified",
    "BFN": "Finance",
    "BIL": "Diversified",
    "BOGA": "Diversified",
    "BOPL": "Plantations",
    "BPPL": "Diversified",
    "BREW": "Beverages",
    "BRR": "Hotels",
    "BRWN": "Diversified",
    "BUKI": "Diversified",
    "CABO": "Diversified",
    "CALF": "Finance",
    "CALH": "Finance",
    "CALT": "Finance",
    "CARE": "Diversified",
    "CARG": "Consumer",
    "CARS": "Diversified",
    "CBNK": "Banking",
    "CCS": "Consumer",
    "CDB": "Finance",
    "CERA": "Manufacturing",
    "CFI": "Diversified",
    "CFIN": "Finance",
    "CFLB": "Property",
    "CFVF": "Finance",
    "CHL": "Diversified",
    "CHMX": "Diversified",
    "CHOT": "Diversified",
    "CIC": "Diversified",
    "CIND": "Diversified",
    "CINS": "Insurance",
    "CINV": "Diversified",
    "CIT": "Diversified",
    "CITH": "Hotels",
    "CITW": "Hotels",
    "CLND": "Property",
    "COCO": "Diversified",
    "COCR": "Finance",
    "COLO": "Diversified",
    "COMB": "Banking",
    "COMD": "Diversified",
    "CONN": "Hotels",
    "COOP": "Insurance",
    "CPRT": "Diversified",
    "CRL": "Finance",
    "CSD": "Diversified",
    "CSLK": "Diversified",
    "CTBL": "Consumer",
    "CTC": "Beverages",
    "CTEA": "Plantations",
    "CTHR": "Diversified",
    "CTLD": "Property",
    "CWL": "Diversified",
    "CWM": "Diversified",
    "DFCC": "Banking",
    "DIAL": "Telecom",
    "DIMO": "Automotive",
    "DIPD": "Manufacturing",
    "DIST": "Beverages",
    "DOCK": "Diversified",
    "DPL": "Manufacturing",
    "EAST": "Diversified",
    "EBCR": "Diversified",
    "ECL": "Diversified",
    "EDEN": "Hotels",
    "ELPL": "Diversified",
    "EMER": "Diversified",
    "EML": "Diversified",
    "ETWO": "Diversified",
    "EXT": "Diversified",
    "FCT": "Finance",
    "GEST": "Diversified",
    "GHLL": "Diversified",
    "GLAS": "Manufacturing",
    "GRAN": "Consumer",
    "GREG": "Diversified",
    "GUAR": "Diversified",
    "HAPU": "Diversified",
    "HARI": "Diversified",
    "HASU": "Construction",
    "HAYC": "Diversified",
    "HAYL": "Diversified",
    "HBS": "Diversified",
    "HDFC": "Banking",
    "HELA": "Textiles",
    "HEXP": "Diversified",
    "HHL": "Diversified",
    "HNB": "Banking",
    "HNBF": "Finance",
    "HOPL": "Diversified",
    "HPFL": "Energy",
    "HPL": "Diversified",
    "HPWR": "Energy",
    "HSIG": "Hotels",
    "HUNA": "Diversified",
    "HUNT": "Diversified",
    "HVA": "Diversified",
    "JAT": "Diversified",
    "JETS": "Diversified",
    "JFP": "Diversified",
    "JINS": "Insurance",
    "JKH": "Diversified",
    "JKL": "Diversified",
    "KAHA": "Diversified",
    "KCAB": "Diversified",
    "KFP": "Beverages",
    "KGAL": "Diversified",
    "KHC": "Diversified",
    "KHL": "Diversified",
    "KOTA": "Diversified",
    "KPHL": "Consumer",
    "KVAL": "Diversified",
    "KZOO": "Property",
    "LALU": "Diversified",
    "LAMB": "Diversified",
    "LCBF": "Finance",
    "LCEY": "Diversified",
    "LDEV": "Finance",
    "LFIN": "Finance",
    "LGIL": "Insurance",
    "LGL": "Energy",
    "LHCL": "Diversified",
    "LHL": "Hotels",
    "LIOC": "Energy",
    "LION": "Diversified",
    "LITE": "Diversified",
    "LLUB": "Diversified",
    "LMF": "Diversified",
    "LOFC": "Finance",
    "LOLC": "Diversified",
    "LPL": "Energy",
    "LPRT": "Diversified",
    "LUMX": "Diversified",
    "LVEF": "Energy",
    "LVEN": "Diversified",
    "LWL": "Manufacturing",
    "MADU": "Diversified",
    "MAL": "Plantations",
    "MARA": "Hotels",
    "MASK": "Diversified",
    "MBSL": "Banking",
    "MCPL": "Plantations",
    "MDL": "Diversified",
    "MEL": "Energy",
    "MELS": "Diversified",
    "MERC": "Finance",
    "MFPE": "Diversified",
    "MGT": "Diversified",
    "MHDL": "Property",
    "MRH": "Diversified",
    "MSL": "Diversified",
    "MULL": "Diversified",
    "NAMU": "Diversified",
    "NDB": "Banking",
    "NEH": "Diversified",
    "NHL": "Diversified",
    "NTB": "Banking",
    "ODEL": "Diversified",
    "OFEQ": "Diversified",
    "ONAL": "Diversified",
    "OSEA": "Diversified",
    "PABC": "Diversified",
    "PACK": "Diversified",
    "PALM": "Plantations",
    "PAP": "Energy",
    "PARA": "Diversified",
    "PARQ": "Diversified",
    "PEG": "Diversified",
    "PHAR": "Diversified",
    "PINS": "Insurance",
    "PKME": "Diversified",
    "PLC": "Finance",
    "PLR": "Diversified",
    "PMB": "Finance",
    "RAL": "Diversified",
    "RCH": "Diversified",
    "RCL": "Diversified",
    "REEF": "Hotels",
    "RENU": "Diversified",
    "REXP": "Diversified",
    "RFL": "Diversified",
    "RGEM": "Diversified",
    "RHL": "Diversified",
    "RHTL": "Hotels",
    "RICH": "Diversified",
    "RIL": "Diversified",
    "RPBH": "Diversified",
    "RWSL": "Diversified",
    "SAMP": "Banking",
    "SCAP": "Finance",
    "SDB": "Banking",
    "SDF": "Finance",
    "SEMB": "Finance",
    "SERV": "Diversified",
    "SEYB": "Banking",
    "SFCL": "Finance",
    "SFIN": "Finance",
    "SHAW": "Diversified",
    "SHL": "Diversified",
    "SHOT": "Diversified",
    "SIGV": "Diversified",
    "SIL": "Diversified",
    "SINH": "Diversified",
    "SINS": "Diversified",
    "SIRA": "Diversified",
    "SLTL": "Telecom",
    "SMOT": "Diversified",
    "SOY": "Diversified",
    "SPEN": "Diversified",
    "STAF": "Diversified",
    "SUN": "Diversified",
    "TAFL": "Diversified",
    "TAJ": "Diversified",
    "TANG": "Diversified",
    "TAP": "Finance",
    "TESS": "Diversified",
    "TILE": "Manufacturing",
    "TJL": "Hotels",
    "TKYO": "Manufacturing",
    "TPL": "Plantations",
    "TRAN": "Diversified",
    "TSML": "Plantations",
    "TYRE": "Diversified",
    "UAL": "Insurance",
    "UBC": "Banking",
    "UBF": "Finance",
    "UCAR": "Diversified",
    "UDPL": "Diversified",
    "UML": "Diversified",
    "VFIN": "Finance",
    "VLL": "Diversified",
    "VONE": "Diversified",
    "VPEL": "Energy",
    "WAPO": "Finance",
    "WATA": "Plantations",
    "WIND": "Diversified",
    "WLTH": "Diversified",
    "YORK": "Diversified",
}


def resolve_ticker(text: str) -> str | None:
    """
    Resolve user input to an official CSE ticker.
    Handles: exact tickers, company names, common aliases, misspellings.
    Does NOT check director names — use resolve_input() for that.
    Returns the official ticker string or None if not found.
    """
    cleaned = text.strip().upper()

    if not cleaned:
        return None

    # Direct ticker match
    if cleaned in TICKER_TO_CSE:
        return cleaned

    # Alias match (case-insensitive)
    lower = text.strip().lower()
    if lower in ALIASES:
        return ALIASES[lower]

    # Partial match — check if input is contained in any alias
    # Require at least 3 chars to prevent false positives
    if len(lower) >= 3:
        for alias, ticker in ALIASES.items():
            if lower in alias or alias in lower:
                return ticker

    return None


def resolve_input(text: str) -> dict:
    """
    Resolve user input to either a single ticker or a director's portfolio.
    Returns:
        {"type": "ticker", "ticker": str} — single stock match
        {"type": "director", "director": dict} — director with multiple tickers
        {"type": "none"} — no match found
    """
    # First try as a ticker (exact or alias)
    ticker = resolve_ticker(text)
    if ticker:
        return {"type": "ticker", "ticker": ticker}

    # Then try as a director name
    from utils.stock_connections import resolve_director
    director = resolve_director(text)
    if director:
        return {"type": "director", "director": director}

    return {"type": "none"}


def get_cse_symbol(ticker: str) -> str | None:
    """Get the full CSE API symbol (e.g., 'KPHL.N0000') for a ticker."""
    return TICKER_TO_CSE.get(ticker)


def get_sector(ticker: str) -> str:
    """Get sector classification for a ticker."""
    return SECTORS.get(ticker, "Unknown")


def get_company_name(ticker: str) -> str:
    """Get human-readable company name from ticker."""
    # Reverse lookup from aliases to find the longest name
    names = [alias for alias, t in ALIASES.items() if t == ticker]
    if names:
        # Return the longest alias (usually the full company name)
        return max(names, key=len).title()
    return ticker


if __name__ == "__main__":
    # Quick test
    test_inputs = ["KPHL", "kapruka", "john keells", "combank", "xyz", "lolc"]
    for inp in test_inputs:
        result = resolve_ticker(inp)
        if result:
            print(f"  '{inp}' -> {result} ({get_company_name(result)}) [{get_sector(result)}]")
        else:
            print(f"  '{inp}' -> NOT FOUND")
